// This file was autogenerated by ../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../lockbox/app.js', ['app'], ['goog.array', 'goog.crypt.base64', 'goog.debug.ErrorHandler', 'goog.dom', 'goog.events', 'goog.events.EventHandler', 'goog.events.EventTarget', 'goog.events.EventType', 'message', 'ssss']);
goog.addDependency('../../../lockbox/comb.js', ['comb'], ['goog.array']);
goog.addDependency('../../../lockbox/gf28.js', ['gf28'], ['goog.array', 'goog.asserts']);
goog.addDependency('../../../lockbox/message.js', ['message'], ['goog.array', 'goog.asserts', 'goog.crypt.Sha1']);
goog.addDependency('../../../lockbox/rng.js', ['rng'], []);
goog.addDependency('../../../lockbox/ssss.js', ['ssss'], ['comb', 'gf28', 'goog.array', 'goog.functions', 'rng']);
